#!/usr/bin/env bash
# Runs ONCE inside the Codespace, after the container is created.
# Generates the page the server will serve. Because this content can only be
# produced by code running inside the container, the served page is itself the
# proof that the devcontainer lifecycle ran in the cloud.
set -euo pipefail

APP_DIR="$(cd "$(dirname "$0")/app" && pwd)"
mkdir -p "$APP_DIR"

cat > "$APP_DIR/index.html" <<HTML
<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>web-hello</title></head>
<body style="font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto;">
  <h1>Hello from Codespaces 👋</h1>
  <p>This page was generated by <code>postCreateCommand</code> when the
     container was created — served from a machine in GitHub's cloud.</p>
  <ul>
    <li><strong>host:</strong> $(hostname)</li>
    <li><strong>user:</strong> $(whoami)</li>
    <li><strong>generated (UTC):</strong> $(date -u +"%Y-%m-%dT%H:%M:%SZ")</li>
  </ul>
</body>
</html>
HTML

echo "postCreate: wrote $APP_DIR/index.html"
