#!/usr/bin/env bash
# Runs on your LAPTOP. Starts the server inside the Codespace, fetches the page
# over ssh, and asserts the lifecycle-generated markers are present.
# Usage: verify.sh <codespace-name>
set -euo pipefail

CS="${1:?usage: verify.sh <codespace-name>}"
WORKDIR="/workspaces/codespaces-probes"

echo "==> starting server inside codespace"
gh codespace ssh -c "$CS" -- "bash $WORKDIR/probes/web-hello/serve.sh && sleep 2"

echo "==> fetching page from inside codespace"
BODY=$(gh codespace ssh -c "$CS" -- 'curl -s http://localhost:8080/')
echo "----- served page -----"
echo "$BODY"
echo "-----------------------"

echo "$BODY" | grep -q "Hello from Codespaces" || { echo "FAIL: greeting marker missing"; exit 1; }
echo "$BODY" | grep -q "host:"                  || { echo "FAIL: host line missing (postCreate did not run?)"; exit 1; }
echo "PASS: page served from the codespace, generated by postCreate"

echo
echo "==> browser check: forwarded port URL(s)"
gh codespace ports -c "$CS"
echo "Open the 8080 'Browse' URL above in your browser to see the page served from the cloud."
